In [1]:
import numpy as np

In [11]:
x = [[1,2,3],[4,5,6]]
x

[[1, 2, 3], [4, 5, 6]]

In [12]:
y = np.array(x)

In [13]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.bincount(y.reshape(-1,1))

ValueError: object too deep for desired array

In [44]:
np.bincount(np.array([1,2,3,12,1,2,12,1,1]))

array([0, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2])

In [47]:
w = y.dot(y.T)
w[0,1] = 0
w

array([[14,  0],
       [32, 77]])

In [52]:

z = np.array([1,0])
z

array([1, 0])

In [53]:
q = w[np.arange(2),z]
q

array([ 0, 32])

In [54]:
w

array([[14,  0],
       [32, 77]])

In [55]:
q

array([ 0, 32])

In [56]:
w-q

array([[ 14, -32],
       [ 32,  45]])

In [61]:
q1 = np.transpose([q])

In [62]:
w-q1

array([[14,  0],
       [ 0, 45]])

In [66]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
a = np.reshape(a, (4,3))

In [70]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
y = [1,2,1,0]

In [74]:
z = a[np.arange(4), y]
z

array([1, 5, 7, 9])

In [78]:
b = a - np.transpose([z])
b

array([[-1,  0,  1],
       [-2, -1,  0],
       [-1,  0,  1],
       [ 0,  1,  2]])

In [81]:
c = np.maximum(0, b)
c

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 2]])

In [84]:
np.sum(c, axis=1)

array([1, 0, 1, 3])

In [10]:
import numpy as np
y = np.array([None, 1, 2, 2, 1])

In [12]:
y

array([None, 1, 2, 2, 1], dtype=object)

In [15]:
if (y == None).any():
    print('None')
else:
    print('yay')

yay


In [1]:
x = {'a':1, 'b':2}

In [2]:
x

{'a': 1, 'b': 2}

In [3]:
x.keys()

dict_keys(['a', 'b'])

In [6]:
for k in x.keys():
    print(k)
    x[k] += 10
    
x

a
b


{'a': 11, 'b': 12}